### ISSUE TITLE
Add support for decoding a raw_id_token

### ISSUE THREAD

**Issue by sauy7** [fishbrain/omniauth-fishbrain#11]
Marketplacer would like to be able to decode the identity token without having to call a cognito endpoint.

Suggestion: Modify the `id_token` method in `VerifiesIdToken` module to accept the token as a parameter

**Comment by sauy7** [comment]
@dalen I think we handle this in rutilus now instead?

**Comment by dalen** [comment]
Yes, handled in other ways now.
